"""Fix case-insensitive name index to use column reference

Revision ID: 1c249d0dfbb5
Revises: add_emp_import_fields
Create Date: 2025-11-21 05:37:23.191211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c249d0dfbb5'
down_revision = 'add_emp_import_fields'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the broken index that uses literal 'name' string
    op.drop_index('ix_employee_name_lower', table_name='employees')

    # Recreate the index correctly using the name column (not literal string)
    op.create_index(
        'ix_employee_name_lower',
        'employees',
        [sa.text('lower(name)')],
        unique=False
    )

    # Clean up temporary table from previous migration
    op.drop_table('_alembic_tmp_employees')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_employees',
    sa.Column('id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('is_supervisor', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('job_title', sa.VARCHAR(length=50), server_default=sa.text("'Event Specialist'"), nullable=False),
    sa.Column('adult_beverage_trained', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('external_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('last_synced', sa.DATETIME(), nullable=True),
    sa.Column('sync_status', sa.VARCHAR(length=20), server_default=sa.text("'pending'"), nullable=True),
    sa.Column('termination_date', sa.DATE(), nullable=True),
    sa.Column('mv_retail_employee_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('crossmark_employee_id', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crossmark_employee_id', name=op.f('uq_employees_crossmark_employee_id')),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('external_id', name=op.f('uq_employees_external_id'))
    )
    # ### end Alembic commands ###
