"""Regenerate missing schema changes

Revision ID: 58becd6c9441
Revises: 0be04acd9951
Create Date: 2025-10-29 02:01:01.591100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58becd6c9441'
down_revision = '0be04acd9951'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_attendance', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_unique_constraint('uix_employee_date', ['employee_id', 'attendance_date'])

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index('idx_employees_active', ['is_active'], unique=False)
        batch_op.create_index('idx_employees_job_title', ['job_title'], unique=False)
        batch_op.create_index('idx_employees_supervisor', ['is_supervisor'], unique=False)
        batch_op.create_index('idx_employees_termination', ['termination_date'], unique=False)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('idx_events_date_range', ['start_datetime', 'due_datetime'], unique=False)
        batch_op.create_index('idx_events_location', ['location_mvid'], unique=False)
        batch_op.create_index('idx_events_scheduled', ['is_scheduled', 'condition'], unique=False)
        batch_op.create_index('idx_events_sync', ['sync_status'], unique=False)
        batch_op.create_index('idx_events_type', ['event_type'], unique=False)

    with op.batch_alter_table('paperwork_templates', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        # Skip dropping indexes that may not exist
        # batch_op.drop_index(batch_op.f('idx_paperwork_templates_active'))
        # batch_op.drop_index(batch_op.f('idx_paperwork_templates_order'))
        batch_op.create_unique_constraint('uix_paperwork_templates_name', ['name'])

    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.create_index('idx_schedules_employee_date', ['employee_id', 'schedule_datetime'], unique=False)
        batch_op.create_index('idx_schedules_event', ['event_ref_num'], unique=False)
        batch_op.create_index('idx_schedules_sync', ['sync_status', 'last_synced'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_index('idx_schedules_sync')
        batch_op.drop_index('idx_schedules_event')
        batch_op.drop_index('idx_schedules_employee_date')

    with op.batch_alter_table('paperwork_templates', schema=None) as batch_op:
        batch_op.drop_constraint('uix_paperwork_templates_name', type_='unique')
        # Skip creating indexes that weren't dropped in upgrade
        # batch_op.create_index(batch_op.f('idx_paperwork_templates_order'), ['display_order'], unique=False)
        # batch_op.create_index(batch_op.f('idx_paperwork_templates_active'), ['is_active'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('idx_events_type')
        batch_op.drop_index('idx_events_sync')
        batch_op.drop_index('idx_events_scheduled')
        batch_op.drop_index('idx_events_location')
        batch_op.drop_index('idx_events_date_range')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index('idx_employees_termination')
        batch_op.drop_index('idx_employees_supervisor')
        batch_op.drop_index('idx_employees_job_title')
        batch_op.drop_index('idx_employees_active')

    with op.batch_alter_table('employee_attendance', schema=None) as batch_op:
        batch_op.drop_constraint('uix_employee_date', type_='unique')
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
